### ISSUE TITLE
Change project name to Jakarta Connectors

### ISSUE THREAD

**Issue by ivargrimstad** [eclipse-ee4j/jca-api#37]
Background information:
https://waynebeaton.wordpress.com/2019/04/04/renaming-java-ee-specifications-for-jakarta-ee/

Checklist:
- [x]  GitHub
- [x]  README file
- [x]  CONTRIBUTING file
- [x]  Eclipse Project under https://projects.eclipse.org/projects/ee4j

**Comment by ivargrimstad** [comment]
Jakarta Connectors?

**Comment by arjantijms** [comment]
>Jakarta Connectors?

+1, "Architecture" is a similar word as "Utilities", "Framework", and "API" used in other specs. I don't think JCA is any more an architecture than JPA is an API and JSF is according to its name neither.

**Comment by njr-11** [comment]
> > Jakarta Connectors?
> 
> +1, "Architecture" is a similar word as "Utilities", "Framework", and "API" used in other specs. I don't think JCA is any more an architecture than JPA is an API and JSF is according to its name neither.

"Architecture" may be semantically unnecessary, but there is value in preserving the current JCA acronym which this spec is already so well known by.  It is important for this spec to be immediately recognized by our user base for what it is: the successor and latest revision of the Java Connector Architecture (JCA) spec.  In order to avoid unnecessary confusion to our user base (that this spec might be incompatible, or is something different altogether), I think we should keep "Architecture" in the name.

**Comment by ivargrimstad** [comment]
By keeping the names simple, we can avoid using acronyms at all. Clearer, simpler, avoiding confusion. JCA would then refer to the Java EE version of the API, which will be around for a long time. And the new fresh Jakarta Connectors refers to the new start under Jakarta EE.

**Comment by smillidge** [comment]
Are we allowed to keep the current acronym? I'm leaning towards Jakarta Connectors. I will put out on the dev list for a committer vote.

**Comment by bshannon** [comment]
We can't use the current acronyms.

I prefer "Jakarta Connectors".

**Comment by frowe** [comment]
I think that's "don't want to" vs. "can't".  On their website, the International Trademark Org noted that in a case involving similar claims, "the court held that the acronym would be protectable as a trademark only if 'the party claiming protection for such an abbreviation shows that the abbreviation has a meaning distinct from the underlying words in the mind of the public.'" A generic acronym like JCA clearly doesn't have such meaning given that acronym is overloaded within just the java namespace (Java Connector Arch and Java Crypto Arch).  And the general public has never heard of JCA.  My vote is to keep JCA for Jakarta Connector Architecture.

**Comment by smillidge** [comment]
My understanding is that Eclipse Foundation want different acronyms. JCA has also always clashed with Java Cryptography Architecture https://docs.oracle.com/javase/8/docs/technotes/guides/security/crypto/CryptoSpec.html

**Comment by bshannon** [comment]
I changed the title of this issue to match the current proposal of "Jakarta Connectors".

**Comment by jmstephensgit** [comment]
There have been several arguments made for keeping the Jakarata Connector
name JCA and I am sure most of the arguments are similar for Java
Crytography.

My vote is to keep JCA for Jakarata Connector Architecture and change Java
Cryptography Architecture to JC if the Eclipse Foundation is requiring
different acronyms.   If its not a required change, then both should keep
using JCA.

Thanks,

James Stephens
WebSphere RRA and J2C Team Lead
hunting@us.ibm.com
Phone: (507)398-7830

**Comment by smillidge** [comment]
We completed a committer vote and the results were;
+4 Jakarta Connector Architecture 
+3 Jakarta Connectors

My understanding is that JCA is not allowed as an acronym so I've asked @jmstephensgit to take it up with the PMC

**Comment by jmstephensgit** [comment]
@smillidge Looking into the acronym, when I have an answer, I will provide an update.

**Comment by kwsutter** [comment]
FYI, the continued use of "common use" acronyms is still an open issue with the Steering Committee (and, in turn, the PMC).  At this point, the recommendation is to avoid the use of acronyms in the Project Names and Descriptions.  Since you are not explicitly calling out the use of JCA when referring to Jakarta Connector Architecture, there really is no problem going that route with the name.  But, ...

To follow the suit of other project renaming exercises, most projects are going "short and sweet".  And, they are avoiding the "API", "Architecture", "Framework" type of terminology.  All of these Specification Projects are assumed to be talking about APIs or Architecture, so why duplicate the name?  To that end, I would suggest going with Jakarta Connectors.  But, that's just me.

**Comment by jmstephensgit** [comment]
@smillidge Based on Kevin's update, Jakarta Connector likely is the best name.   Not sure if we need to request a new vote or if my vote change just makes it  +3 Jakarta Connector Architecture
+4 Jakarta Connectors

**Comment by waynebeaton** [comment]
Unless there is some push back, I'm moving this forward with "Jakarta Connectors".

**Comment by bshannon** [comment]
> Unless there is some push back, I'm moving this forward with "Jakarta Connectors".

+1

**Comment by smillidge** [comment]
Closing as done
